export { ReactComponent as home } from './home.svg';
export { ReactComponent as chartBar } from './chart-bar.svg';
export { ReactComponent as homeO } from './home-o.svg';
export { ReactComponent as apps } from './apps.svg';
export { ReactComponent as arrowBottom } from './arrow-bottom.svg';
export { ReactComponent as arrowDown } from './arrow-down.svg';
export { ReactComponent as arrowLeft } from './arrow-left.svg';
export { ReactComponent as arrowRight } from './arrow-right.svg';
export { ReactComponent as longArrowLeft } from './long-arrow-left.svg';
export { ReactComponent as longArrowUp } from './long-arrow-up.svg';
export { ReactComponent as longArrowDown } from './long-arrow-down.svg';
export { ReactComponent as longArrowRight } from './long-arrow-right.svg';
export { ReactComponent as arrows } from './arrows.svg';
export { ReactComponent as arrowsAlt } from './arrows-alt.svg';
export { ReactComponent as arrowsH } from './arrows-h.svg';
export { ReactComponent as arrowsV } from './arrows-v.svg';
export { ReactComponent as expand } from './expand.svg';
export { ReactComponent as compress } from './compress.svg';
export { ReactComponent as arrowTop } from './arrow-top.svg';
export { ReactComponent as plus } from './plus.svg';
export { ReactComponent as plusMin } from './plus-min.svg';
export { ReactComponent as arrowUp } from './arrow-up.svg';
export { ReactComponent as plusCircle } from './plus-circle.svg';
export { ReactComponent as plusCircleO } from './plus-circle-o.svg';
export { ReactComponent as plusSquare } from './plus-square.svg';
export { ReactComponent as plusSquareO } from './plus-square-o.svg';
export { ReactComponent as minus } from './minus.svg';
export { ReactComponent as minusMin } from './minus-min.svg';
export { ReactComponent as bars } from './bars.svg';
export { ReactComponent as minusCircle } from './minus-circle.svg';
export { ReactComponent as minusCircleO } from './minus-circle-o.svg';
export { ReactComponent as minusSquare } from './minus-square.svg';
export { ReactComponent as minusSquareO } from './minus-square-o.svg';
export { ReactComponent as close } from './close.svg';
export { ReactComponent as closeMin } from './close-min.svg';
export { ReactComponent as catched } from './catched.svg';
export { ReactComponent as closeCircle } from './close-circle.svg';
export { ReactComponent as closeCircleO } from './close-circle-o.svg';
export { ReactComponent as closeSquare } from './close-square.svg';
export { ReactComponent as closeSquareO } from './close-square-o.svg';
export { ReactComponent as check } from './check.svg';
export { ReactComponent as checkMin } from './check-min.svg';
export { ReactComponent as checkThin } from './check-thin.svg';
export { ReactComponent as checkCircle } from './check-circle.svg';
export { ReactComponent as checkCircleO } from './check-circle-o.svg';
export { ReactComponent as checkSquare } from './check-square, check-box.svg';
export { ReactComponent as checkSquareO } from './check-square-o, checkbox-checked.svg';
export { ReactComponent as caretUp } from './caret-up.svg';
export { ReactComponent as caretUpMin } from './caret-up-min.svg';
export { ReactComponent as caretUpCircle } from './caret-up-circle.svg';
export { ReactComponent as caretUpCircleO } from './caret-up-circle-o.svg';
export { ReactComponent as caretUpSquare } from './caret-up-square.svg';
export { ReactComponent as caretUpSquareO } from './caret-up-square-o.svg';
export { ReactComponent as caretDown } from './caret-down.svg';
export { ReactComponent as caretDownMin } from './caret-down-min.svg';
export { ReactComponent as caretDownCircle } from './caret-down-circle.svg';
export { ReactComponent as caretDownCircleO } from './caret-down-circle-o.svg';
export { ReactComponent as caretDownSquare } from './caret-down-square.svg';
export { ReactComponent as caretDownSquareO } from './caret-down-square-o.svg';
export { ReactComponent as angleLeft } from './angle-left.svg';
export { ReactComponent as angleLeftMin } from './angle-left-min.svg';
export { ReactComponent as angleLeftThin } from './angle-left-thin.svg';
export { ReactComponent as angleRight } from './angle-right.svg';
export { ReactComponent as angleRightMin } from './angle-right-min.svg';
export { ReactComponent as angleRightThin } from './angle-right-thin.svg';
export { ReactComponent as angleDown } from './angle-down.svg';
export { ReactComponent as angleDownMin } from './angle-down-min.svg';
export { ReactComponent as angleDownThin } from './angle-down-thin.svg';
export { ReactComponent as angleUp } from './angle-up.svg';
export { ReactComponent as angleUpMin } from './angle-up-min.svg';
export { ReactComponent as angleUpThin } from './angle-up-thin.svg';
export { ReactComponent as compareArrows } from './compare-arrows.svg';
export { ReactComponent as dashboard } from './dashboard.svg';
export { ReactComponent as ellipsisV } from './ellipsis-v.svg';
export { ReactComponent as ellipsisH } from './ellipsis-h.svg';
export { ReactComponent as scroll } from './scroll.svg';
export { ReactComponent as powerOff } from './power-off.svg';
export { ReactComponent as alt } from './alt.svg';
export { ReactComponent as command } from './command.svg';
export { ReactComponent as esc } from './esc.svg';
export { ReactComponent as eyeO } from './eye-o.svg';
export { ReactComponent as eye } from './eye.svg';
export { ReactComponent as eyeOffO } from './eye-off-o, eye-slash2.svg';
export { ReactComponent as eyeOff } from './eye-off, eye-slash.svg';
export { ReactComponent as expandSquare } from './expand-square.svg';
export { ReactComponent as compressSquare } from './compress-square.svg';
export { ReactComponent as alignJustify } from './align-justify.svg';
export { ReactComponent as alignLeft } from './align-left.svg';
export { ReactComponent as alignCenter } from './align-center.svg';
export { ReactComponent as alignRight } from './align-right.svg';
export { ReactComponent as indent } from './indent.svg';
export { ReactComponent as dedent } from './dedent.svg';
export { ReactComponent as listDot } from './list-dot, list-ul.svg';
export { ReactComponent as listSquare } from './list-square, list-ul-square.svg';
export { ReactComponent as dashboardO } from './dashboard-o.svg';
export { ReactComponent as list } from './list, list-ul-l.svg';
export { ReactComponent as dragHandle } from './drag-handle.svg';
export { ReactComponent as flag } from './flag.svg';
export { ReactComponent as flagO } from './flag-o.svg';
export { ReactComponent as logIn } from './log-in.svg';
export { ReactComponent as lock } from './lock.svg';
export { ReactComponent as unlock } from './unlock.svg';
export { ReactComponent as lockO } from './lock-o.svg';
export { ReactComponent as unlockO } from './unlock-o.svg';
export { ReactComponent as paragraph } from './paragraph.svg';
export { ReactComponent as strikethrough } from './strikethrough.svg';
export { ReactComponent as bold } from './bold.svg';
export { ReactComponent as underline } from './underline.svg';
export { ReactComponent as italic } from './italic.svg';
export { ReactComponent as caps } from './caps.svg';
export { ReactComponent as trash } from './trash.svg';
export { ReactComponent as trashO } from './trash-o.svg';
export { ReactComponent as eraser } from './eraser.svg';
export { ReactComponent as eraserO } from './eraser-o.svg';
export { ReactComponent as logOut } from './log-out.svg';
export { ReactComponent as refresh } from './refresh.svg';
export { ReactComponent as sortAsc } from './sort-asc, lineheight-plus.svg';
export { ReactComponent as sortDesc } from './sort-desc, lineheight-minus.svg';
export { ReactComponent as lineHeight } from './line-height, lineheight.svg';
export { ReactComponent as renew } from './renew.svg';
export { ReactComponent as rotateRight } from './rotate-right.svg';
export { ReactComponent as rotateLeft } from './rotate-left.svg';
export { ReactComponent as search } from './search, magnifier.svg';
export { ReactComponent as zoomIn } from './zoom-in, magnifier-expand.svg';
export { ReactComponent as zoomOut } from './zoom-out, magnifier-reduce.svg';
export { ReactComponent as colorDropper } from './color-dropper, eye-dropper.svg';
export { ReactComponent as subdirectory } from './subdirectory.svg';
export { ReactComponent as textType } from './text-type, type.svg';
export { ReactComponent as externalLink } from './external-link.svg';
export { ReactComponent as subdirectoryArrow } from './subdirectory-arrow.svg';
export { ReactComponent as sync } from './sync.svg';
export { ReactComponent as viewArray } from './view-array.svg';
export { ReactComponent as viewCarousel } from './view-carousel.svg';
export { ReactComponent as viewColumn } from './view-column.svg';
export { ReactComponent as cog } from './cog.svg';
export { ReactComponent as borderAll } from './border-all.svg';
export { ReactComponent as layout } from './layout, layout-top.svg';
export { ReactComponent as layoutFull } from './layout-full.svg';
export { ReactComponent as layoutSnb } from './layout-snb, layout-top-left.svg';
export { ReactComponent as layoutAside } from './layout-aside, layout-top-right.svg';
export { ReactComponent as layoutColumn } from './layout-column, layout-top-three.svg';
export { ReactComponent as viewDay } from './view-day.svg';
export { ReactComponent as layoutO } from './layout-o.svg';
export { ReactComponent as layoutFullO } from './layout-full-o.svg';
export { ReactComponent as layoutSnbO } from './layout-snb-o.svg';
export { ReactComponent as layoutAsideO } from './layout-aside-o.svg';
export { ReactComponent as layoutColumnO } from './layout-column-o.svg';
export { ReactComponent as viewList } from './view-list.svg';
export { ReactComponent as scissors } from './scissors.svg';
export { ReactComponent as palette } from './palette, color.svg';
export { ReactComponent as dragVertical } from './drag-vertical.svg';
export { ReactComponent as viewModule } from './view-module.svg';
export { ReactComponent as document } from './document, form.svg';
export { ReactComponent as crop } from './crop.svg';
export { ReactComponent as viewStream } from './view-stream.svg';
export { ReactComponent as wrench } from './wrench.svg';
export { ReactComponent as bell } from './bell.svg';
export { ReactComponent as bellO } from './bell-o.svg';
export { ReactComponent as bellOff } from './bell-off, bell-slash.svg';
export { ReactComponent as bellOffO } from './bell-off-o.svg';
export { ReactComponent as calendar } from './calendar.svg';
export { ReactComponent as calendarAdd } from './calendar-add.svg';
export { ReactComponent as calendarRemove } from './calendar-remove.svg';
export { ReactComponent as calendarCancle } from './calendar-cancle.svg';
export { ReactComponent as calendarCheck } from './calendar-check.svg';
export { ReactComponent as calendarList } from './calendar-list.svg';
export { ReactComponent as info } from './info, information-circle.svg';
export { ReactComponent as infoO } from './info-o.svg';
export { ReactComponent as new } from './new.svg';
export { ReactComponent as newO } from './new-o.svg';
export { ReactComponent as error } from './error.svg';
export { ReactComponent as errorO } from './error-o.svg';
export { ReactComponent as helpO } from './help-o.svg';
export { ReactComponent as help } from './help, unknown-circle.svg';
export { ReactComponent as ban } from './ban, slash-circle.svg';
export { ReactComponent as closeThin } from './close-thin.svg';
export { ReactComponent as cut } from './cut.svg';
export { ReactComponent as label } from './label.svg';
export { ReactComponent as labelO } from './label-o.svg';
export { ReactComponent as libraryAdd } from './library-add.svg';
export { ReactComponent as libraryBookmark } from './library-bookmark, tagged-book.svg';
export { ReactComponent as watch } from './watch.svg';
export { ReactComponent as mouse } from './mouse.svg';
export { ReactComponent as sdcard } from './sdcard.svg';
export { ReactComponent as usbDrive } from './usb-drive.svg';
export { ReactComponent as save } from './save.svg';
export { ReactComponent as diskette } from './diskette.svg';
export { ReactComponent as print } from './print, social-print.svg';
export { ReactComponent as fax } from './fax.svg';
export { ReactComponent as lightbulb } from './lightbulb, idea.svg';
export { ReactComponent as lightbulbO } from './lightbulb-o.svg';
export { ReactComponent as link } from './link.svg';
export { ReactComponent as minusThin } from './minus-thin.svg';
export { ReactComponent as package } from './package, archive.svg';
export { ReactComponent as pen } from './pen.svg';
export { ReactComponent as penO } from './pen-o.svg';
export { ReactComponent as plusThin } from './plus-thin.svg';
export { ReactComponent as radioboxBlank } from './radiobox-blank.svg';
export { ReactComponent as radioboxChecked } from './radiobox-checked.svg';
export { ReactComponent as redo } from './redo.svg';
export { ReactComponent as switchOff } from './switch-off.svg';
export { ReactComponent as switchOn } from './switch-on.svg';
export { ReactComponent as toggleOff } from './toggle-off.svg';
export { ReactComponent as webcam } from './webcam.svg';
export { ReactComponent as toggleOn } from './toggle-on.svg';
export { ReactComponent as projector } from './projector.svg';
export { ReactComponent as presentation } from './presentation.svg';
export { ReactComponent as plug } from './plug.svg';
export { ReactComponent as globus } from './globus.svg';
export { ReactComponent as undo } from './undo.svg';
export { ReactComponent as call } from './call, phone.svg';
export { ReactComponent as callOutgoing } from './call-outgoing.svg';
export { ReactComponent as callMissed } from './call-missed.svg';
export { ReactComponent as callIncoming } from './call-incoming, call-reception.svg';
export { ReactComponent as comment } from './comment.svg';
export { ReactComponent as commentO } from './comment-o.svg';
export { ReactComponent as filter } from './filter, funnel.svg';
export { ReactComponent as crown } from './crown.svg';
export { ReactComponent as browser } from './browser.svg';
export { ReactComponent as browserText } from './browser-text.svg';
export { ReactComponent as emoticonHappy } from './emoticon-happy, happy-face.svg';
export { ReactComponent as emoticonBad } from './emoticon-bad.svg';
export { ReactComponent as emoticonBadO } from './emoticon-bad-o.svg';
export { ReactComponent as emoticonCool } from './emoticon-cool.svg';
export { ReactComponent as emoticonCoolO } from './emoticon-cool-o.svg';
export { ReactComponent as emoticonDevil } from './emoticon-devil, angry-face.svg';
export { ReactComponent as emoticonDevilO } from './emoticon-devil-o.svg';
export { ReactComponent as emoticonSmiley } from './emoticon-smiley, smiley-face.svg';
export { ReactComponent as rssSquare } from './rss-square.svg';
export { ReactComponent as emoticonSmileyO } from './emoticon-smiley-o.svg';
export { ReactComponent as centralSignal } from './central-signal.svg';
export { ReactComponent as centralRouter } from './central-router.svg';
export { ReactComponent as shareAlt } from './share-alt.svg';
export { ReactComponent as shareAltO } from './share-alt-o.svg';
export { ReactComponent as emoticonNeutral } from './emoticon-neutral, neutral-face.svg';
export { ReactComponent as emoticonNeutralO } from './emoticon-neutral-o.svg';
export { ReactComponent as emoticonHappyO } from './emoticon-happy-o.svg';
export { ReactComponent as emoticonSad } from './emoticon-sad, sad-face.svg';
export { ReactComponent as emoticonSadO } from './emoticon-sad-o.svg';
export { ReactComponent as forum } from './forum, comments.svg';
export { ReactComponent as forumO } from './forum-o.svg';
export { ReactComponent as profile } from './profile, user-circle.svg';
export { ReactComponent as user } from './user.svg';
export { ReactComponent as userAddress } from './user-address.svg';
export { ReactComponent as userO } from './user-o.svg';
export { ReactComponent as antenna } from './antenna.svg';
export { ReactComponent as userPlus } from './user-plus.svg';
export { ReactComponent as userPlusO } from './user-plus-o.svg';
export { ReactComponent as users } from './users.svg';
export { ReactComponent as share } from './share, share-l.svg';
export { ReactComponent as cartO } from './cart-o.svg';
export { ReactComponent as cartAdd } from './cart-add.svg';
export { ReactComponent as cartRemove } from './cart-remove.svg';
export { ReactComponent as basket } from './basket.svg';
export { ReactComponent as barcode } from './barcode.svg';
export { ReactComponent as qrCode } from './qr-code.svg';
export { ReactComponent as box } from './box.svg';
export { ReactComponent as fragile } from './fragile.svg';
export { ReactComponent as coupon } from './coupon.svg';
export { ReactComponent as usersO } from './users-o.svg';
export { ReactComponent as shop } from './shop.svg';
export { ReactComponent as mail } from './mail, envelope, social-email.svg';
export { ReactComponent as mailO } from './mail-o.svg';
export { ReactComponent as mailRead } from './mail-read, envelope-open.svg';
export { ReactComponent as mailReadO } from './mail-read-o.svg';
export { ReactComponent as at } from './at.svg';
export { ReactComponent as send } from './send, paper-plane.svg';
export { ReactComponent as replyAll } from './reply-all.svg';
export { ReactComponent as reply } from './reply.svg';
export { ReactComponent as checkboxBlank } from './checkbox-blank.svg';
export { ReactComponent as star } from './star.svg';
export { ReactComponent as heart } from './heart.svg';
export { ReactComponent as heartO } from './heart-o.svg';
export { ReactComponent as speech } from './speech.svg';
export { ReactComponent as speechO } from './speech-o.svg';
export { ReactComponent as message } from './message.svg';
export { ReactComponent as messageO } from './message-o.svg';
export { ReactComponent as starO } from './star-o.svg';
export { ReactComponent as usersPlus } from './users-plus.svg';
export { ReactComponent as videoCall } from './video-call, xi-film.svg';
export { ReactComponent as voicemail } from './voicemail.svg';
export { ReactComponent as note } from './note.svg';
export { ReactComponent as noteO } from './note-o.svg';
export { ReactComponent as bookmark } from './bookmark.svg';
export { ReactComponent as bookmarkO } from './bookmark-o.svg';
export { ReactComponent as alarm } from './alarm.svg';
export { ReactComponent as alarmO } from './alarm-o.svg';
export { ReactComponent as alarmOff } from './alarm-off.svg';
export { ReactComponent as handPaper } from './hand-paper.svg';
export { ReactComponent as key } from './key.svg';
export { ReactComponent as security } from './security, shield.svg';
export { ReactComponent as shieldChecked } from './shield-checked, check-shield.svg';
export { ReactComponent as shieldCheckedO } from './shield-checked-o.svg';
export { ReactComponent as snooze } from './snooze.svg';
export { ReactComponent as thumbsUp } from './thumbs-up.svg';
export { ReactComponent as thumbsDown } from './thumbs-down.svg';
export { ReactComponent as profileO } from './profile-o.svg';
export { ReactComponent as time } from './time.svg';
export { ReactComponent as timeO } from './time-o.svg';
export { ReactComponent as warning } from './warning.svg';
export { ReactComponent as group } from './group, community.svg';
export { ReactComponent as woman } from './woman.svg';
export { ReactComponent as man } from './man.svg';
export { ReactComponent as toilet } from './toilet.svg';
export { ReactComponent as borderBottom } from './border-bottom.svg';
export { ReactComponent as borderClear } from './border-clear.svg';
export { ReactComponent as book } from './book.svg';
export { ReactComponent as bookO } from './book-o.svg';
export { ReactComponent as tag } from './tag.svg';
export { ReactComponent as tags } from './tags.svg';
export { ReactComponent as trophy } from './trophy.svg';
export { ReactComponent as borderColor } from './border-color.svg';
export { ReactComponent as giftO } from './gift-o.svg';
export { ReactComponent as pause } from './pause.svg';
export { ReactComponent as pauseCircleO } from './pause-circle-o.svg';
export { ReactComponent as pauseCircle } from './pause-circle.svg';
export { ReactComponent as play } from './play, caret-right.svg';
export { ReactComponent as playCircleO } from './play-circle-o.svg';
export { ReactComponent as playCircle } from './play-circle.svg';
export { ReactComponent as stop } from './stop.svg';
export { ReactComponent as eject } from './eject.svg';
export { ReactComponent as stepBackward } from './step-backward.svg';
export { ReactComponent as stepForward } from './step-forward.svg';
export { ReactComponent as borderHorizontal } from './border-horizontal.svg';
export { ReactComponent as borderInner } from './border-inner.svg';
export { ReactComponent as backward } from './backward.svg';
export { ReactComponent as forward } from './forward.svg';
export { ReactComponent as borderLeft } from './border-left.svg';
export { ReactComponent as cameraO } from './camera-o.svg';
export { ReactComponent as camera } from './camera.svg';
export { ReactComponent as videocamO } from './videocam-o.svg';
export { ReactComponent as videocam } from './videocam, video-camera.svg';
export { ReactComponent as imageO } from './image-o.svg';
export { ReactComponent as borderOuter } from './border-outer.svg';
export { ReactComponent as image } from './image.svg';
export { ReactComponent as borderRight } from './border-right.svg';
export { ReactComponent as borderStyle } from './border-style.svg';
export { ReactComponent as exchange } from './exchange, barter.svg';
export { ReactComponent as borderTop } from './border-top.svg';
export { ReactComponent as equalizerThin } from './equalizer-thin.svg';
export { ReactComponent as microphoneO } from './microphone-o.svg';
export { ReactComponent as microphone } from './microphone.svg';
export { ReactComponent as microphoneOff } from './microphone-off, microphone-slash.svg';
export { ReactComponent as volumeMute } from './volume-mute, volume.svg';
export { ReactComponent as volumeDown } from './volume-down, volume-min.svg';
export { ReactComponent as volumeUp } from './volume-up, volume-max.svg';
export { ReactComponent as borderVertical } from './border-vertical.svg';
export { ReactComponent as code } from './code.svg';
export { ReactComponent as colorFill } from './color-fill.svg';
export { ReactComponent as colorHelper } from './color-helper.svg';
export { ReactComponent as speaker } from './speaker.svg';
export { ReactComponent as album } from './album, record-play, cd-r.svg';
export { ReactComponent as emoticon } from './emoticon, emoji, face.svg';
export { ReactComponent as font } from './font.svg';
export { ReactComponent as headset } from './headset.svg';
export { ReactComponent as music } from './music.svg';
export { ReactComponent as lineStyle } from './line-style.svg';
export { ReactComponent as lineWeight } from './line-weight.svg';
export { ReactComponent as linkBroken } from './link-broken, unlink.svg';
export { ReactComponent as chartPyramid } from './chart-pyramid.svg';
export { ReactComponent as linkInsert } from './link-insert, link-l.svg';
export { ReactComponent as listNumber } from './list-number, list-ol.svg';
export { ReactComponent as omega } from './omega.svg';
export { ReactComponent as opacity } from './opacity.svg';
export { ReactComponent as yuan } from './yuan.svg';
export { ReactComponent as won } from './won.svg';
export { ReactComponent as yen } from './yen.svg';
export { ReactComponent as pound } from './pound.svg';
export { ReactComponent as euro } from './euro.svg';
export { ReactComponent as rial } from './rial.svg';
export { ReactComponent as dollar } from './dollar.svg';
export { ReactComponent as peso } from './peso.svg';
export { ReactComponent as rupee } from './rupee.svg';
export { ReactComponent as creditCard } from './credit-card.svg';
export { ReactComponent as overscan } from './overscan.svg';
export { ReactComponent as money } from './money.svg';
export { ReactComponent as piggyBank } from './piggy-bank.svg';
export { ReactComponent as strongbox } from './strongbox.svg';
export { ReactComponent as briefcase } from './briefcase.svg';
export { ReactComponent as percent } from './percent.svg';
export { ReactComponent as calculator } from './calculator.svg';
export { ReactComponent as paperclip } from './paperclip.svg';
export { ReactComponent as fileO } from './file-o.svg';
export { ReactComponent as fileAddO } from './file-add-o.svg';
export { ReactComponent as fileRemoveO } from './file-remove-o.svg';
export { ReactComponent as fileTextO } from './file-text-o.svg';
export { ReactComponent as documentsO } from './documents-o.svg';
export { ReactComponent as fileImageO } from './file-image-o.svg';
export { ReactComponent as fileVideoO } from './file-video-o.svg';
export { ReactComponent as fileMusicO } from './file-music-o.svg';
export { ReactComponent as fileCodeO } from './file-code-o.svg';
export { ReactComponent as fileZipO } from './file-zip-o.svg';
export { ReactComponent as fileUploadO } from './file-upload-o.svg';
export { ReactComponent as fileDownloadO } from './file-download-o.svg';
export { ReactComponent as fileCheckO } from './file-check-o.svg';
export { ReactComponent as folderO } from './folder-o.svg';
export { ReactComponent as folderAddO } from './folder-add-o.svg';
export { ReactComponent as folderRemoveO } from './folder-remove-o.svg';
export { ReactComponent as folderCheckO } from './folder-check-o.svg';
export { ReactComponent as folderUploadO } from './folder-upload-o.svg';
export { ReactComponent as folderDownloadO } from './folder-download-o.svg';
export { ReactComponent as folderZipO } from './folder-zip-o.svg';
export { ReactComponent as file } from './file.svg';
export { ReactComponent as fileAdd } from './file-add.svg';
export { ReactComponent as fileRemove } from './file-remove.svg';
export { ReactComponent as fileText } from './file-text.svg';
export { ReactComponent as documents } from './documents, stack-paper.svg';
export { ReactComponent as fileImage } from './file-image.svg';
export { ReactComponent as fileVideo } from './file-video.svg';
export { ReactComponent as fileMusic } from './file-music.svg';
export { ReactComponent as fileCode } from './file-code.svg';
export { ReactComponent as fileZip } from './file-zip.svg';
export { ReactComponent as fileUpload } from './file-upload.svg';
export { ReactComponent as fileDownload } from './file-download.svg';
export { ReactComponent as fileCheck } from './file-check.svg';
export { ReactComponent as folder } from './folder.svg';
export { ReactComponent as folderAdd } from './folder-add.svg';
export { ReactComponent as folderRemove } from './folder-remove.svg';
export { ReactComponent as folderCheck } from './folder-check.svg';
export { ReactComponent as folderUpload } from './folder-upload.svg';
export { ReactComponent as folderDownload } from './folder-download.svg';
export { ReactComponent as folderZip } from './folder-zip.svg';
export { ReactComponent as folderOpen } from './folder-open.svg';
export { ReactComponent as spellcheck } from './spellcheck.svg';
export { ReactComponent as textColor } from './text-color.svg';
export { ReactComponent as registered } from './registered.svg';
export { ReactComponent as trademark } from './trademark.svg';
export { ReactComponent as ccCc } from './cc-cc.svg';
export { ReactComponent as ccBy } from './cc-by.svg';
export { ReactComponent as ccSa } from './cc-sa.svg';
export { ReactComponent as ccNd } from './cc-nd.svg';
export { ReactComponent as ccNc } from './cc-nc.svg';
export { ReactComponent as ccNcEu } from './cc-nc-eu.svg';
export { ReactComponent as ccNcJp } from './cc-nc-jp.svg';
export { ReactComponent as ccRemix } from './cc-remix.svg';
export { ReactComponent as ccPd } from './cc-pd.svg';
export { ReactComponent as ccSampling } from './cc-sampling.svg';
export { ReactComponent as ccZero } from './cc-zero.svg';
export { ReactComponent as ccShare } from './cc-share.svg';
export { ReactComponent as textFormat } from './text-format.svg';
export { ReactComponent as textSize } from './text-size.svg';
export { ReactComponent as transform } from './transform.svg';
export { ReactComponent as translate } from './translate.svg';
export { ReactComponent as valignBottom } from './valign-bottom.svg';
export { ReactComponent as valignCenter } from './valign-center.svg';
export { ReactComponent as valignTop } from './valign-top.svg';
export { ReactComponent as airplay } from './airplay.svg';
export { ReactComponent as alarmClock } from './alarm-clock.svg';
export { ReactComponent as alarmClockO } from './alarm-clock-o.svg';
export { ReactComponent as alarmClockOff } from './alarm-clock-off.svg';
export { ReactComponent as backspace } from './backspace.svg';
export { ReactComponent as battery } from './battery, battery-full.svg';
export { ReactComponent as battery10 } from './battery-10.svg';
export { ReactComponent as battery20 } from './battery-20.svg';
export { ReactComponent as battery30 } from './battery-30.svg';
export { ReactComponent as battery40 } from './battery-40.svg';
export { ReactComponent as flickr } from './flickr.svg';
export { ReactComponent as battery50 } from './battery-50.svg';
export { ReactComponent as battery60 } from './battery-60.svg';
export { ReactComponent as battery70 } from './battery-70.svg';
export { ReactComponent as battery80 } from './battery-80.svg';
export { ReactComponent as battery90 } from './battery-90.svg';
export { ReactComponent as batteryO } from './battery-o, battery-min.svg';
export { ReactComponent as bluetooth } from './bluetooth.svg';
export { ReactComponent as bluetoothOff } from './bluetooth-off.svg';
export { ReactComponent as bluetoothOn } from './bluetooth-on.svg';
export { ReactComponent as bluetoothSearch } from './bluetooth-search.svg';
export { ReactComponent as brightness } from './brightness.svg';
export { ReactComponent as capslock } from './capslock.svg';
export { ReactComponent as clock } from './clock.svg';
export { ReactComponent as clockO } from './clock-o.svg';
export { ReactComponent as contrast } from './contrast.svg';
export { ReactComponent as desktop } from './desktop, monitor.svg';
export { ReactComponent as devices } from './devices.svg';
export { ReactComponent as enter } from './enter.svg';
export { ReactComponent as flashlight } from './flashlight.svg';
export { ReactComponent as flashlightOff } from './flashlight-off.svg';
export { ReactComponent as flightOff } from './flight-off.svg';
export { ReactComponent as flightOn } from './flight-on.svg';
export { ReactComponent as gamepad } from './gamepad.svg';
export { ReactComponent as gps } from './gps.svg';
export { ReactComponent as gpsNone } from './gps-none.svg';
export { ReactComponent as gpsOff } from './gps-off.svg';
export { ReactComponent as hdd } from './hdd.svg';
export { ReactComponent as hdmi } from './hdmi.svg';
export { ReactComponent as keyboard } from './keyboard.svg';
export { ReactComponent as keyboardO } from './keyboard-o.svg';
export { ReactComponent as laptop } from './laptop.svg';
export { ReactComponent as lockRotation } from './lock-rotation.svg';
export { ReactComponent as chip } from './chip.svg';
export { ReactComponent as chipO } from './chip-o.svg';
export { ReactComponent as mobile } from './mobile.svg';
export { ReactComponent as mousePointer } from './mouse-pointer.svg';
export { ReactComponent as router } from './router, wifi-router.svg';
export { ReactComponent as routerO } from './router-o.svg';
export { ReactComponent as signal } from './signal.svg';
export { ReactComponent as signal1 } from './signal-1.svg';
export { ReactComponent as signal2 } from './signal-2.svg';
export { ReactComponent as signal3 } from './signal-3.svg';
export { ReactComponent as signal4 } from './signal-4.svg';
export { ReactComponent as signalNone } from './signal-none.svg';
export { ReactComponent as spaceBar } from './space-bar.svg';
export { ReactComponent as tab } from './tab.svg';
export { ReactComponent as tablet } from './tablet.svg';
export { ReactComponent as touch } from './touch.svg';
export { ReactComponent as tv } from './tv.svg';
export { ReactComponent as usb } from './usb.svg';
export { ReactComponent as wifi } from './wifi, wifi-signal.svg';
export { ReactComponent as wifiSignalMid } from './wifi-signal-mid.svg';
export { ReactComponent as wifiSignalMin } from './wifi-signal-min.svg';
export { ReactComponent as wifiSignalOff } from './wifi-signal-off.svg';
export { ReactComponent as chartBarSquare } from './chart-bar-square.svg';
export { ReactComponent as chartLine } from './chart-line.svg';
export { ReactComponent as chartPie } from './chart-pie.svg';
export { ReactComponent as chartPieO } from './chart-pie-o.svg';
export { ReactComponent as equalizer } from './equalizer, volume-bar.svg';
export { ReactComponent as exposure } from './exposure.svg';
export { ReactComponent as fastForward } from './fast-forward.svg';
export { ReactComponent as fastBackward } from './fast-backward.svg';
export { ReactComponent as flash } from './flash.svg';
export { ReactComponent as flashOff } from './flash-off.svg';
export { ReactComponent as focusCenter } from './focus-center.svg';
export { ReactComponent as focusFrame } from './focus-frame.svg';
export { ReactComponent as fullMoon } from './full-moon, fullmoon.svg';
export { ReactComponent as halfMoon } from './half-moon, halfmoon.svg';
export { ReactComponent as moon } from './moon.svg';
export { ReactComponent as night } from './night.svg';
export { ReactComponent as focusWeak } from './focus-weak.svg';
export { ReactComponent as windsock } from './windsock.svg';
export { ReactComponent as libraryBooks } from './library-books.svg';
export { ReactComponent as snowCrystal } from './snow-crystal, snow.svg';
export { ReactComponent as libraryBooksO } from './library-books-o.svg';
export { ReactComponent as libraryImage } from './library-image.svg';
export { ReactComponent as libraryImageO } from './library-image-o.svg';
export { ReactComponent as libraryMusic } from './library-music.svg';
export { ReactComponent as libraryVideo } from './library-video.svg';
export { ReactComponent as movie } from './movie.svg';
export { ReactComponent as movieO } from './movie-o.svg';
export { ReactComponent as pacman } from './pacman.svg';
export { ReactComponent as paper } from './paper.svg';
export { ReactComponent as paperO } from './paper-o.svg';
export { ReactComponent as radio } from './radio.svg';
export { ReactComponent as recording } from './recording, record.svg';
export { ReactComponent as map } from './map, map-folding.svg';
export { ReactComponent as mapO } from './map-o.svg';
export { ReactComponent as recordingStop } from './recording-stop.svg';
export { ReactComponent as repeat } from './repeat.svg';
export { ReactComponent as repeatOne } from './repeat-one.svg';
export { ReactComponent as shuffle } from './shuffle.svg';
export { ReactComponent as glass } from './glass.svg';
export { ReactComponent as timer } from './timer.svg';
export { ReactComponent as timerO } from './timer-o.svg';
export { ReactComponent as market } from './market, shopping-bag.svg';
export { ReactComponent as pharmacy } from './pharmacy.svg';
export { ReactComponent as medicine } from './medicine.svg';
export { ReactComponent as laundry } from './laundry.svg';
export { ReactComponent as timerOffO } from './timer-off-o.svg';
export { ReactComponent as timerSand } from './timer-sand, sandwatch-min.svg';
export { ReactComponent as timerSandO } from './timer-sand-o.svg';
export { ReactComponent as florist } from './florist.svg';
export { ReactComponent as trendingDown } from './trending-down, decline.svg';
export { ReactComponent as hlz } from './hlz.svg';
export { ReactComponent as park } from './park.svg';
export { ReactComponent as trendingFlat } from './trending-flat.svg';
export { ReactComponent as trendingUp } from './trending-up, rise.svg';
export { ReactComponent as tune } from './tune.svg';
export { ReactComponent as volumeOff } from './volume-off, volume-slash.svg';
export { ReactComponent as airplane } from './airplane.svg';
export { ReactComponent as all } from './all.svg';
export { ReactComponent as flightTakeoff } from './flight-takeoff, flight.svg';
export { ReactComponent as flightLand } from './flight-land.svg';
export { ReactComponent as bank } from './bank, bank-o.svg';
export { ReactComponent as beach } from './beach.svg';
export { ReactComponent as bicycle } from './bicycle.svg';
export { ReactComponent as building } from './building.svg';
export { ReactComponent as bus } from './bus.svg';
export { ReactComponent as business } from './business.svg';
export { ReactComponent as cafe } from './cafe.svg';
export { ReactComponent as hamburgerOut } from './hamburger-out.svg';
export { ReactComponent as hamburgerBack } from './hamburger-back.svg';
export { ReactComponent as cake } from './cake.svg';
export { ReactComponent as car } from './car.svg';
export { ReactComponent as church } from './church.svg';
export { ReactComponent as city } from './city.svg';
export { ReactComponent as compass } from './compass.svg';
export { ReactComponent as compassO } from './compass-o.svg';
export { ReactComponent as convenienceStore } from './convenience-store.svg';
export { ReactComponent as directions } from './directions.svg';
export { ReactComponent as factory } from './factory.svg';
export { ReactComponent as fitnessCenter } from './fitness-center.svg';
export { ReactComponent as garden } from './garden.svg';
export { ReactComponent as gasStation } from './gas-station.svg';
export { ReactComponent as golf } from './golf.svg';
export { ReactComponent as handPointing } from './hand-pointing.svg';
export { ReactComponent as hospital } from './hospital.svg';
export { ReactComponent as hotel } from './hotel.svg';
export { ReactComponent as library } from './library.svg';
export { ReactComponent as locationArrow } from './location-arrow.svg';
export { ReactComponent as maker } from './maker, marker-circle.svg';
export { ReactComponent as markerCheck } from './marker-check.svg';
export { ReactComponent as markerPlus } from './marker-plus.svg';
export { ReactComponent as motorcycle } from './motorcycle.svg';
export { ReactComponent as myLocation } from './my-location.svg';
export { ReactComponent as navigation } from './navigation.svg';
export { ReactComponent as makerDrop } from './maker-drop, map-marker.svg';
export { ReactComponent as pool } from './pool.svg';
export { ReactComponent as pregnantWoman } from './pregnant-woman, maternity.svg';
export { ReactComponent as restaurant } from './restaurant.svg';
export { ReactComponent as run } from './run.svg';
export { ReactComponent as school } from './school.svg';
export { ReactComponent as ship } from './ship.svg';
export { ReactComponent as spa } from './spa.svg';
export { ReactComponent as stroller } from './stroller.svg';
export { ReactComponent as subway } from './subway.svg';
export { ReactComponent as taxi } from './taxi.svg';
export { ReactComponent as theater } from './theater, film.svg';
export { ReactComponent as traffic } from './traffic.svg';
export { ReactComponent as train } from './train.svg';
export { ReactComponent as walk } from './walk, walking.svg';
export { ReactComponent as wheelchair } from './wheelchair.svg';
export { ReactComponent as cart } from './cart.svg';
export { ReactComponent as gift } from './gift, present.svg';
export { ReactComponent as receipt } from './receipt.svg';
export { ReactComponent as truck } from './truck.svg';
export { ReactComponent as wallet } from './wallet.svg';
export { ReactComponent as attachment } from './attachment.svg';
export { ReactComponent as cloud } from './cloud.svg';
export { ReactComponent as cloudDownload } from './cloud-download.svg';
export { ReactComponent as cloudDownloadO } from './cloud-download-o.svg';
export { ReactComponent as cloudO } from './cloud-o.svg';
export { ReactComponent as cloudOff } from './cloud-off.svg';
export { ReactComponent as cloudUpload } from './cloud-upload.svg';
export { ReactComponent as cloudUploadO } from './cloud-upload-o.svg';
export { ReactComponent as download } from './download.svg';
export { ReactComponent as folderShared } from './folder-shared.svg';
export { ReactComponent as upload } from './upload.svg';
export { ReactComponent as accessibility } from './accessibility.svg';
export { ReactComponent as branch } from './branch.svg';
export { ReactComponent as bug } from './bug.svg';
export { ReactComponent as cookie } from './cookie.svg';
export { ReactComponent as css3 } from './css3.svg';
export { ReactComponent as fingerprint } from './fingerprint.svg';
export { ReactComponent as fork } from './fork, code-fork.svg';
export { ReactComponent as html5 } from './html5.svg';
export { ReactComponent as javascript } from './javascript.svg';
export { ReactComponent as csharp } from './csharp.svg';
export { ReactComponent as laravel } from './laravel.svg';
export { ReactComponent as log } from './log.svg';
export { ReactComponent as merge } from './merge.svg';
export { ReactComponent as milestone } from './milestone.svg';
export { ReactComponent as networkCompany } from './network-company.svg';
export { ReactComponent as networkFolder } from './network-folder.svg';
export { ReactComponent as networkHome } from './network-home, home-network.svg';
export { ReactComponent as networkPublic } from './network-public, cloud-network.svg';
export { ReactComponent as php } from './php.svg';
export { ReactComponent as pullRequests } from './pull-requests.svg';
export { ReactComponent as puzzle } from './puzzle.svg';
export { ReactComponent as python } from './python.svg';
export { ReactComponent as rss } from './rss, social-rssfeed.svg';
export { ReactComponent as server } from './server.svg';
export { ReactComponent as networkServer } from './network-server.svg';
export { ReactComponent as sitemap } from './sitemap.svg';
export { ReactComponent as sitemapO } from './sitemap-o.svg';
export { ReactComponent as crescent } from './crescent.svg';
export { ReactComponent as cloudy } from './cloudy.svg';
export { ReactComponent as fog } from './fog.svg';
export { ReactComponent as foggy } from './foggy.svg';
export { ReactComponent as lightning } from './lightning.svg';
export { ReactComponent as partlyCloudy } from './partly-cloudy.svg';
export { ReactComponent as pouring } from './pouring, rain.svg';
export { ReactComponent as snowy } from './snowy, heavy-snow.svg';
export { ReactComponent as sun } from './sun.svg';
export { ReactComponent as sunO } from './sun-o.svg';
export { ReactComponent as sunset } from './sunset.svg';
export { ReactComponent as sunsetDown } from './sunset-down.svg';
export { ReactComponent as sunsetUp } from './sunset-up.svg';
export { ReactComponent as thermometer } from './thermometer.svg';
export { ReactComponent as tint } from './tint, humidity.svg';
export { ReactComponent as tintO } from './tint-o.svg';
export { ReactComponent as tornado } from './tornado.svg';
export { ReactComponent as umbrella } from './umbrella.svg';
export { ReactComponent as umbrellaO } from './umbrella-o.svg';
export { ReactComponent as windy } from './windy, wind.svg';
export { ReactComponent as windyVariant } from './windy-variant.svg';
export { ReactComponent as copyleft } from './copyleft.svg';
export { ReactComponent as copyright } from './copyright.svg';
export { ReactComponent as px } from './500px.svg';
export { ReactComponent as adobe } from './adobe.svg';
export { ReactComponent as amazon } from './amazon.svg';
export { ReactComponent as android } from './android.svg';
export { ReactComponent as apple } from './apple.svg';
export { ReactComponent as beats } from './beats.svg';
export { ReactComponent as behance } from './behance.svg';
export { ReactComponent as bing } from './bing.svg';
export { ReactComponent as bitbucket } from './bitbucket.svg';
export { ReactComponent as blackberry } from './blackberry.svg';
export { ReactComponent as blogger } from './blogger.svg';
export { ReactComponent as silverstripe } from './silverstripe.svg';
export { ReactComponent as ccAmex } from './cc-amex.svg';
export { ReactComponent as ccDiscover } from './cc-discover.svg';
export { ReactComponent as ccMastercard } from './cc-mastercard.svg';
export { ReactComponent as ccPaypal } from './cc-paypal.svg';
export { ReactComponent as ccStripe } from './cc-stripe.svg';
export { ReactComponent as ccVisa } from './cc-visa.svg';
export { ReactComponent as chrome } from './chrome.svg';
export { ReactComponent as codepen } from './codepen.svg';
export { ReactComponent as connectdevelop } from './connectdevelop.svg';
export { ReactComponent as d2 } from './d2.svg';
export { ReactComponent as dashcube } from './dashcube.svg';
export { ReactComponent as delicious } from './delicious.svg';
export { ReactComponent as deviantart } from './deviantart.svg';
export { ReactComponent as digg } from './digg.svg';
export { ReactComponent as disqus } from './disqus.svg';
export { ReactComponent as dribbble } from './dribbble.svg';
export { ReactComponent as dropbox } from './dropbox.svg';
export { ReactComponent as drupal } from './drupal.svg';
export { ReactComponent as edge } from './edge.svg';
export { ReactComponent as evernote } from './evernote.svg';
export { ReactComponent as facebook } from './facebook.svg';
export { ReactComponent as facebookMessenger } from './facebook-messenger.svg';
export { ReactComponent as facebookOfficial } from './facebook-official.svg';
export { ReactComponent as feedly } from './feedly.svg';
export { ReactComponent as firefox } from './firefox.svg';
export { ReactComponent as flickrSquare } from './flickr-square.svg';
export { ReactComponent as foursquare } from './foursquare.svg';
export { ReactComponent as ghost } from './ghost.svg';
export { ReactComponent as git } from './git.svg';
export { ReactComponent as gitSymbol } from './git-symbol.svg';
export { ReactComponent as github } from './github.svg';
export { ReactComponent as githubAlt } from './github-alt.svg';
export { ReactComponent as gmail } from './gmail.svg';
export { ReactComponent as google } from './google.svg';
export { ReactComponent as googlePlay } from './google-play.svg';
export { ReactComponent as googlePlus } from './google-plus.svg';
export { ReactComponent as googleWallet } from './google-wallet.svg';
export { ReactComponent as gratipay } from './gratipay.svg';
export { ReactComponent as hangouts } from './hangouts.svg';
export { ReactComponent as hunie } from './hunie.svg';
export { ReactComponent as illustrator } from './illustrator.svg';
export { ReactComponent as illustratorCircle } from './illustrator-circle.svg';
export { ReactComponent as instagram } from './instagram.svg';
export { ReactComponent as internetExplorer } from './internet-explorer.svg';
export { ReactComponent as jira } from './jira.svg';
export { ReactComponent as joomla } from './joomla.svg';
export { ReactComponent as jsfiddle } from './jsfiddle.svg';
export { ReactComponent as kakaotalk } from './kakaotalk.svg';
export { ReactComponent as kakaostory } from './kakaostory.svg';
export { ReactComponent as kickstarter } from './kickstarter.svg';
export { ReactComponent as line } from './line.svg';
export { ReactComponent as lineMessenger } from './line-messenger.svg';
export { ReactComponent as linkedin } from './linkedin.svg';
export { ReactComponent as linkedinSquare } from './linkedin-square.svg';
export { ReactComponent as linux } from './linux.svg';
export { ReactComponent as magento } from './magento.svg';
export { ReactComponent as maxcdn } from './maxcdn.svg';
export { ReactComponent as medium } from './medium.svg';
export { ReactComponent as naver } from './naver.svg';
export { ReactComponent as naverSquare } from './naver-square.svg';
export { ReactComponent as office } from './office.svg';
export { ReactComponent as opencart } from './opencart.svg';
export { ReactComponent as opera } from './opera.svg';
export { ReactComponent as oscommerce } from './oscommerce.svg';
export { ReactComponent as path } from './path.svg';
export { ReactComponent as paypal } from './paypal.svg';
export { ReactComponent as photoshop } from './photoshop.svg';
export { ReactComponent as photoshopCircle } from './photoshop-circle.svg';
export { ReactComponent as pinterest } from './pinterest.svg';
export { ReactComponent as pinterestP } from './pinterest-p.svg';
export { ReactComponent as pocket } from './pocket.svg';
export { ReactComponent as qq } from './qq.svg';
export { ReactComponent as quicktime } from './quicktime.svg';
export { ReactComponent as reddit } from './reddit.svg';
export { ReactComponent as renren } from './renren.svg';
export { ReactComponent as safari } from './safari.svg';
export { ReactComponent as sellsy } from './sellsy.svg';
export { ReactComponent as simplybuilt } from './simplybuilt.svg';
export { ReactComponent as sketch } from './sketch.svg';
export { ReactComponent as skype } from './skype.svg';
export { ReactComponent as slack } from './slack.svg';
export { ReactComponent as slideshare } from './slideshare.svg';
export { ReactComponent as soundcloud } from './soundcloud.svg';
export { ReactComponent as spotify } from './spotify.svg';
export { ReactComponent as stackExchange } from './stack-exchange.svg';
export { ReactComponent as stackOverflow } from './stack-overflow.svg';
export { ReactComponent as steam } from './steam.svg';
export { ReactComponent as steamSquare } from './steam-square.svg';
export { ReactComponent as stumbleupon } from './stumbleupon.svg';
export { ReactComponent as stumbleuponCircle } from './stumbleupon-circle.svg';
export { ReactComponent as telegram } from './telegram.svg';
export { ReactComponent as tencentWeibo } from './tencent-weibo.svg';
export { ReactComponent as trello } from './trello.svg';
export { ReactComponent as tumblr } from './tumblr.svg';
export { ReactComponent as tumblrSquare } from './tumblr-square.svg';
export { ReactComponent as twich } from './twich.svg';
export { ReactComponent as twitter } from './twitter.svg';
export { ReactComponent as ubercart } from './ubercart.svg';
export { ReactComponent as ubuntu } from './ubuntu.svg';
export { ReactComponent as ubuntuCircle } from './ubuntu-circle.svg';
export { ReactComponent as vimeo } from './vimeo.svg';
export { ReactComponent as vine } from './vine.svg';
export { ReactComponent as vk } from './vk.svg';
export { ReactComponent as wechat } from './wechat.svg';
export { ReactComponent as whatsapp } from './whatsapp.svg';
export { ReactComponent as wikipedia } from './wikipedia.svg';
export { ReactComponent as windows } from './windows.svg';
export { ReactComponent as wordpress } from './wordpress.svg';
export { ReactComponent as wordpressOfficial } from './wordpress-official.svg';
export { ReactComponent as xe } from './xe.svg';
export { ReactComponent as xing } from './xing.svg';
export { ReactComponent as xpressengine } from './xpressengine.svg';
export { ReactComponent as yahoo } from './yahoo.svg';
export { ReactComponent as yelp } from './yelp.svg';
export { ReactComponent as youtube } from './youtube.svg';
export { ReactComponent as youtubePlay } from './youtube-play.svg';
export { ReactComponent as spinner1 } from './spinner-1.svg';
export { ReactComponent as spinner2 } from './spinner-2.svg';
export { ReactComponent as spinner3 } from './spinner-3.svg';
export { ReactComponent as spinner4 } from './spinner-4.svg';
export { ReactComponent as spinner5 } from './spinner-5.svg';
